name: Build Electron App for all OS

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm install

      - name: Package App
        run: npx electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
